package com.ercanbeyen.restaurantapplication.util;

import com.ercanbeyen.restaurantapplication.exception.InternalServerErrorException;
import lombok.experimental.UtilityClass;

import java.util.Optional;

@UtilityClass
public class QRCodeUtil {
    private static final String COMPANY_DOMAIN = "http://localhost:8080/";
    private static final int MAXIMUM_QR_CODE_CONTENT_LENGTH = 100;

    public void validateQRContent(String qrContent) {
        if (Optional.ofNullable(qrContent).isEmpty() || qrContent.isEmpty()) {
            throw new IllegalArgumentException("QR code content cannot be empty.");
        }

        if (!qrContent.startsWith(COMPANY_DOMAIN)) {
            throw new SecurityException("Invalid resource! This QR code was not generated by an authorized authority.");
        }

        if (qrContent.length() > MAXIMUM_QR_CODE_CONTENT_LENGTH) {
            throw new IllegalArgumentException("QR code content is too long.");
        }
    }

    public void validateDecodedText(String decodedText) {
        if (decodedText == null || decodedText.trim().isEmpty()) {
            throw new InternalServerErrorException("Error occurred while reading the QR code.");
        }
    }
}
